### ISSUE TITLE
create_leads_list returns TypeError

### ISSUE THREAD

**Issue by cdbmgrdn** [VonStruddle/PyHunter#56]
Hello,

When using the `create_leads_list` function, it returns a TypeError.

Relevant code:
```
from pyhunter import PyHunter

HUNTER_API_KEY = 'working_api_key'

hunter = PyHunter(HUNTER_API_KEY)

hunter.create_leads_list('test list')
```

Error:
```
Traceback (most recent call last):
  File "/Users/xxx/Desktop/xxx/lead_admin.py", line 14, in <module>
    hunter.create_leads_list('test list')
  File "/Users/xxx/Desktop/xxx/venv/lib/python3.7/site-packages/pyhunter/pyhunter.py", line 450, in create_leads_list
    return self._query_hunter(endpoint, params, 'post', payload)
  File "/Users/cadeboomgarden/Desktop/ugp_lg/venv/lib/python3.7/site-packages/pyhunter/pyhunter.py", line 17, in _query_hunter
    request_kwargs.setdefault(json=payload)
TypeError: setdefault() takes no keyword arguments
```

**Comment by VonStruddle** [comment]
Hey 👋

I'll check that asap!
